### ISSUE TITLE
Encoding Auto-Detection with UTF-8 BOM

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#111]
I have a log file with an UTF-8 BOM
It is mostly ASCII with some fancy Unicode characters as separators
I'm using klogg 19.9.0.479 with Encoding menu set as Auto,

When new lines are added to the log file, sometimes the display temporarily switch to ASCII (displaying the UTF-8 chars wrongly) and then back to UTF-8
This might be related to issue #53 but the worst part is that the file has an explicit UTF-8 BOM, so the auto-detection of encoding should be straightforward and not subject to guessing.

**Comment by variar** [comment]
I see several possible issues here:
 - redoing encoding detection when new data is added to file despite the fact that in this case encoding can't change (otherwise full reindexing will be done)
 - using only new data to detect encoding when doing partial indexing
 - no applying encoding detection immediately during full reindexing (#53)

**Comment by variar** [comment]
Should be fixed in builds >= 19.11.0.500

**Comment by wiz0u** [comment]
Totally broken in build 19.11.0.500 :(
Encoding set as Auto, opening a file with explicit UTF-8 BOM marker
=> shows up as "System" with BOM characters visible at the beginning of the file

**Comment by variar** [comment]
Ooops, sorry for that. Should be good at 19.11.0.504

**Comment by wiz0u** [comment]
Seems good now.
