### ISSUE TITLE
Some usability issues

### ISSUE THREAD

**Issue by shvez** [variar/klogg#168]
Hi, there.

I use klogg everyday. Really nice tool. here some minor issues i have:
- if cursor is in one of the edit boxes after pressing Ctrl+F or Ctrl-S I can not use 'F' shortcut anymore.
- if I opened search by pressing 'Ctrl-F' I can not close it by pressing 'Esc' or 'Ctrl-F' second time. So, I also have to use mouse to get rid of it

best,
ilya

**Comment by alvlapo** [comment]
Hi @shvez , of course the hotkey does not work when the any input field is active, because the hotkey does not have a modifier (ctrl or shift) and is recognized as a character for search. 
I suggest changing the behaviour of the search bar: 
* ctrl+F - opening the search bar, 
* Esc - closing the search bar, 
* ctrl+F (on active serach bar) - the next search result, 
* shift + F - the previous search result. 

@variar how do you like my suggestion?

**Comment by variar** [comment]
Esc should close search bar. I think I've already seen an issue for that (maybe, it was in glogg).

Changing "Search next"/"Search previous" shortcuts might cause some trouble for those used to "standard" F3/Shift+F3 combinations. I'm not sure about it.

**Comment by variar** [comment]
In builds 21.05.0.956+ `Esc` should reset focus from quickfind/regex search boxes. This way hitting `Esc` and then `F` should work for toggling follow mode

**Comment by shvez** [comment]
very good. will try it out

**Comment by shvez** [comment]
it works good. I think it is much more convenient than before
