### ISSUE TITLE
Problems on HiDPI monitor on Windows

### ISSUE THREAD

**Issue by variar** [variar/klogg#186]
![klogg-hidpi-01](https://user-images.githubusercontent.com/1620716/80742627-5c30b180-8b24-11ea-9c5d-6c76d9700b35.png)
![klogg-hidpi-02](https://user-images.githubusercontent.com/1620716/80742631-605ccf00-8b24-11ea-8ff6-a8c0a0a98c0b.png)

**Comment by variar** [comment]
Might be caused by fractional scaling and rounding. See https://invent.kde.org/kde/krita/-/merge_requests/2

**Comment by variar** [comment]
Reproduced only when using klogg via Remote Desktop. Might be Qt issue

**Comment by lekrus** [comment]
Hello,

I also have the issue with fonts on HiDPI laptop with 125% fonts increase (default suggested Windows setting). Following QT link above, if I set
QT_SCALE_FACTOR_ROUNDING_POLICY=Round

the issue is gone.

Before:
![image](https://user-images.githubusercontent.com/14861921/82045464-cebe9700-96b7-11ea-8892-1dcf1ae43b1d.png)
After the setting is set:
![image](https://user-images.githubusercontent.com/14861921/82045569-fd3c7200-96b7-11ea-9c6e-c3b890c026dc.png)

Hope that might be useful (probably you could add a checkbox in the settings to switch to the previous behavior?)

Thanks!

**Comment by variar** [comment]
Thanks @lekrus, this should definitely be a configurable setting. Too unclear how to make it work in all cases automagically.

**Comment by variar** [comment]
Should be ok with new settings. Don't know what else can be done now. Feel free to reopen.

**Comment by lekrus** [comment]
the latest dev release works just fine, thanks!
