### ISSUE TITLE
Sign package for MacOS

### ISSUE THREAD

**Issue by variar** [variar/klogg#217]
When klogg is started from downloaded DMG package MacOS flags it as coming from untrusted source. There should be a way to codesign DMG to avoid this.

**Comment by variar** [comment]
Ok, codesigning seems to work fine. Now need to figure put notarization quest

**Comment by variar** [comment]
Notarization is part of ci workflow now

**Comment by BenXM** [comment]
Unfortunately, new release 20.12 seems to have this codesigning issue again, at least on my Mojave MacBook.

**Comment by variar** [comment]
Sorry, @BenXM,  but I can't reproduce this in my Catalina VM. Could you provide some screenshots showing the warnings that you are getting?

**Comment by BenXM** [comment]
Hi Anton,
Sorry, just noticing your reply now.  Below is a screenshot.  I'm using a locked-down corporate Mojave MacBook, so I have no permission to change security on it.  Thanks for looking into this, I love using the 20.04 version of this app!


<img width="488" alt="Screen Shot 2021-05-13 at 9 39 29 AM" src="https://user-images.githubusercontent.com/45547025/118134637-262d3b00-b3d0-11eb-9390-db7f596452fc.png">

**Comment by variar** [comment]
@BenXM does this happen with [CI builds](https://github.com/variar/klogg/releases/tag/continuous-osx)? According to Apple  my code-signing certificate should be valid until 2025/10/03.

**Comment by variar** [comment]
And does sha256 sum of downloaded dmg match with that on release page?

**Comment by BenXM** [comment]
Hi Anton, it's actually working now with the latest build from the CI builds link you sent.  Please bear with me because I'm a Mac noob after a lifetime on Windows...

When I tried opening the `dmg` file itself, I got the popup below.  But I'd read somewhere about a `hdiutil` utility.  So I ran this:
`hdiutil attach -noverify ~/Downloads/klogg-21.05.0.959-OSX.dmg`

And it let me attach `klogg.dmg`.  From there, I did what I usually do to install apps outside the /Applications directory -- I created a folder somewhere else, renamed it to `klogg21.app`, then did _Show Package Contents_ on both the original and my `klogg21.app`, and copied the Contents from the original to `klogg21.app`.  Now I can launch the app successfully from this new `klogg21.app`!

I _think_ I'd tried this with the 20.12 release, but I'm not sure.  Anyway, I'm happy to have this version up and running, with all the cool new stuff you've added!  Thanks so much!  And if you can give me any other tips re installing apps without adiministrative security privileges, I'd be very grateful.

Best regards,  -- Ben

![image](https://user-images.githubusercontent.com/45547025/118188501-7925e300-b40e-11eb-87d0-0e02df73d12e.png)

**Comment by BenXM** [comment]
One other note:  I just tried the command you suggested anyway, just to see what it would do.  Here is the result:

$ **spctl -a -vvv -t install ~/Downloads/klogg-21.05.0.959-OSX.dmg**

~/Downloads/klogg-21.05.0.959-OSX.dmg: rejected
source=Unnotarized Developer ID
origin=Developer ID Application: Anton Filimonov (GAW773U324)
$

**Comment by variar** [comment]
Thanks for the feedback! I'll ask my colleagues at work to check this issue as I can't reproduce it in my development environment.

**Comment by variar** [comment]
Unfortunately, my colleges can't reproduce the issue.

**Comment by variar** [comment]
Seems to work in all environments that I am able to check.
