### ISSUE TITLE
Chocolatey scripts pulling incorrect release

### ISSUE THREAD

**Issue by Lim-Dul** [variar/klogg#293]
When the release version is incremented in Chocolatey, it seems to be still pulling the incorrect release from GitHub (latest?).
At the moment of writing (2021-05-03) GitHub is still on 20.12.0.813 and the Chocolatey script for 20.12.1.813 is thus pulling the incorrect version.

Steps to reproduce:
1a. If klogg already installed at release 20.12.0.813 or lower, run `choco upgrade all` in elevated PS prompt
1b. If klogg not installed, run `choco install klogg` in elevatated PS prompt
1c. If klogg already installed via Chocolatey in the latest version, run `choco install klogg --force` in elevatated PS prompt
2. Observe downloaded installer and version after launching klogg

![image](https://user-images.githubusercontent.com/428324/116877515-55002000-ac1e-11eb-8581-bf5c6aa888de.png)
![image](https://user-images.githubusercontent.com/428324/116876901-7ca2b880-ac1d-11eb-8f47-c55ad3dbbffd.png)

**Comment by variar** [comment]
Jfrog is shutting down Bintray service where binaries for chocolatey were hosted. I had to update chocolatey scripts to point to Github release. Unfortunately, as far as I understand chocolatey rules, it is not possible to change scripts without changing package version. That's why chocolatey package version is changed but binaries are the same.

I am going to release next stable version in a couple of months, so recompiling old one just to increase version number seems to much work.

**Comment by Lim-Dul** [comment]
Ah! Understood! Thanks for the explanation. Outside of Chocolatey I'm on nightly anyways, was just confused. So everything should re-align with the next stable version.
