### ISSUE TITLE
Implement jittered coloring of regex matches

### ISSUE THREAD

**Issue by DVMirchev** [variar/klogg#330]
Imagine I have a regex for matching IPv4 addresses:

`[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}`

and I check **Highlight only match** which will colour all matches with the same colour.

However, not all IPs will be the same so I would appreciate having each match coloured slightly differently with a slight deviation from the selected Fore and Back Colors.

I expect a less than 5% deviation from the RGB colour to be registerable by the human eye and thus we will know that - yes, these are IPs but different ones.

**Comment by variar** [comment]
That is an interesting idea. I suspect that the deviation will vary a lot depending on monitor settings and color perception. So that should be configurable. I see it as a checkbox somewhere in pattern highlight settings and a spinbox to enter deviation. 

Maybe instead of specifying deviation it will be better to set two colors for Fore/Back, and then build a gradient based on them. I'll have to experiment a bit.

**Comment by DVMirchev** [comment]
I've worked with RGB colours a long time ago and I'm not very into the Color Theory but I guess the trivial approach might work - just add/subtract random numbers less than say 10-20 from the selected colours. However, it'll have to keep track of all regex matches so it can colourize the already colourized match with the same colour or something. Not sure what the performance impact will be.

Just throwing ideas. Sorry for not having time to implement it myself

**Comment by variar** [comment]
That turned out to be quite easy to implement. I take crc32 of matched portion of the line, use it as a seed for random generator and change brightness of highlight colors. This way same matches get same color. Amount of change can be configured in settings. Should be in builds 21.06.0.1021+.

**Comment by DVMirchev** [comment]
Awesome! Thank you!
