### ISSUE TITLE
Line numbers in main view isn't sticky between restarts for portable 20.12.0.813

### ISSUE THREAD

**Issue by stridskoma2** [variar/klogg#349]
Details for the issue
--------------------

#### What did you do?
Enabled line numbers in main view

#### What did you expect to see?
Still there after restart of the app

#### What did you see instead?
Gone

Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built on 2020-12-24 from commit 576b91d) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19043) [x86_64]
> and Qt 5.15.2

**Comment by stridskoma2** [comment]
Btw this is using the portable version

**Comment by variar** [comment]
Thanks, looks like I can reproduce this issue. I'll investigate it further.

**Comment by stridskoma2** [comment]
Cool. Really liking the app - just installed yesterday. You guys don't have https://www.buymeacoffee.com? If u sign up I'll send over a few ☕

**Comment by variar** [comment]
Should be fixed in current [dev-builds](https://github.com/variar/klogg/releases/tag/continuous-win). 

I've added a coffee link to the list of sponsor options for this repository:
![Screenshot_20210625_143927](https://user-images.githubusercontent.com/1620716/123419666-2caff480-d5c3-11eb-98b3-1ea5d8d80dde.png)

**Comment by stridskoma2** [comment]
Sent u some coffee. Will try it out today. Thanks for quick turnaround although not a showstopper bug

**Comment by stridskoma2** [comment]
Works a charm, thanks!
