### ISSUE TITLE
Allow font scaling with Mouse wheel

### ISSUE THREAD

**Issue by Max1234-Ita** [variar/klogg#359]
This is more a new feature suggestion than real issue.
I use Klogg very much, and keep moving its window across different displays on my laptop: the integrated one, 14-in, very high density (i.e. 160 dpi) and an external 24-in monitor, which is standard 96dpi.

It would be very comfortable if I could adjust the font size by just rotating my mouse wheel, like i do in other Editors (i.e. Notepad++, PyCharm, etc.)

Thanks for your attention!
Max

**Comment by variar** [comment]
Than can be useful!

Can be tested in 21.07.0.1066.

**Comment by Max1234-Ita** [comment]
I downloaded v. 21.07.0.1069 from Release Continuous, but unfortunately I can't test it at the moment: the Symantec antivirus Heuristic Engine in my Company's laptop keeps complaining that's not a well-known software and puts the executable to quarantine every time I run it; Of course, I'm not allowed to add rule exceptions.

The strange thing is that I'm already using v. 20.12.0.813 in the very same PC, without issues of any kind.
I'll try with another PC, if I can get one.
Thank you so much, anyway!

Max

**Comment by jeffjensen** [comment]
WFM!  Thank you.

**Comment by variar** [comment]
@Max1234-Ita that issues with Symantec is very unfortunate. I'm afraid not much can be done from my side. The best way to avoid this is to buy code signing certificate for Windows from some trusted authority like Symantec :), but it is hard for individual developer both because these certificates are expensive (I'm already paying for Apple codesigning certificate for Klogg) and because most providers can issue certificates only for a company, not an individual. 

Version 20.12.0.813 has been around for much longer and might have built some trust from antivirus standpoint.

**Comment by Max1234-Ita** [comment]
Thanks for your reply. 
Yes, I think the same. Maybe the heuristics take into account the number of computers where that particular version is present when the system is scanned. 

Anyway, today I went to the Quarantine menu in Symantec antivirus and just restored the Klogg executable back in place.
It seems to work for the moment, let's hope well...

Oh, and BTW the font scaling feature works like a charm! :-)

Cheers,
Max

**Comment by Max1234-Ita** [comment]
Actually, I think I found a little issue: when I "zoom out" and the font has reaches its smallest size, if I keep turning the wheel in the same direction, it is somehow restored to "normal" (maybe the size defined in the configuration menu?).
I think it should keep the smallest size until the mouse wheel is turned in the opposite way. (it works fine when I keep  "zooming in" and the font reaches the maximum size allowed).

Max

**Comment by variar** [comment]
Fixed in 21.07.0.1073
