### ISSUE TITLE
encoding detection is not working correctly.

### ISSUE THREAD

**Issue by GW-Kang** [variar/klogg#447]
Details for the issue
--------------------

#### What did you do?
I opened a file encoded in EUC-KR. I have attached the file with the problem.

#### What did you expect to see?
It should be automatically detected as EUC-KR.

#### What did you see instead?
It was detected as windows-1252, and some 2-byte characters look unrecognizable.

Useful extra information
-------------------------
> Klogg version 20.12.0.813 (built on 2020-12-24 from commit 576b91d) [built for x86_64-little_endian-llp64]
> running on Windows 10 Version 2009 (winnt/10.0.19044) [x86_64]
> and Qt 5.15.
[EUC-KR encoding.Log](https://github.com/variar/klogg/files/7999354/EUC-KR.encoding.Log)
2

**Comment by variar** [comment]
Thank you very much for the sample text!

**Comment by variar** [comment]
Klogg uses [uchardet](https://github.com/freedesktop/uchardet) for encoding detection. For the sample text it guesses windows-1252. Probably if there were more 2-byte characters it would detect correct encoding. Unfortunately, this can't be fixed in klogg. If most of your files are in EUC-KR, it is possible to turn off automatic encoding detection select single preferred encoding.
