### ISSUE TITLE
[Windows 11] Opening Export highlighter file dialog crashes klogg 

### ISSUE THREAD

**Issue by DVMirchev** [variar/klogg#506]
Go go Highlighters, select one, and click on the Export button. 

The file dialog opens and in less than a second, the app crashes. Without any user input.

Reproduced on Windows 11 with klogg 22.06. I first encountered it with an older version, then installed the latest release with the hope it is fixed but still crashes.

**Comment by variar** [comment]
Unfortunately, that looks like a known issue on Windows 11. On some Windows 11 systems klogg crashes when trying to show an open file dialog (https://github.com/variar/klogg/issues/484). This is due to an incompatibility between Intel TBB memory allocator and some Windows libraries. In this case setting environmental variable TBB_MALLOC_DISABLE_REPLACEMENT to 1 disables TBB memory allocator, and klogg works as expected.
