### ISSUE TITLE
Find another way of hosting DEB/RPM repos instead of JFrog

### ISSUE THREAD

**Issue by variar** [variar/klogg#613]
JFrog announced closing of their free tier. They do have progamm to support open source projects, but it is impossible to use because of some export regulations
![image](https://github.com/variar/klogg/assets/1620716/b5f3e039-fb94-4e83-a250-baa53cef8132)

Looks like klogg has to move to Ubuntu PPA / OpenSuse OBS.

**Comment by jeffjensen** [comment]
:-(

While the Ubunutu/OpenSuse repos may work out best, possibly another
consideration is the Maven Central Repository, publish via the OSSRH:
https://central.sonatype.org/
https://central.sonatype.org/publish/

It's heavily Java focused but the repo supports *many* artifact types
https://help.sonatype.com/repomanager3/nexus-repository-administration/formats

The automated uploads focus on using Maven, Gradle, and SBT; you could make
a simple upload build with one of those (e.g. a Maven POM that finalizes
and uploads the artifacts).  Otherwise, can manually upload.
https://www.sonatype.com/products/integrations

**Comment by variar** [comment]
Thanks! That could be an option for APT packages.

**Comment by akwala** [comment]
[Relevant thread on Reddit](https://www.reddit.com/r/linux/comments/13yld5j/jfrog_killing_their_free_debrpm_repo_tier_in_30/) had these suggestions, and this is the info I found about the hosted ones that offer both DEB and RPM:

- [The OBS public instance](https://build.opensuse.org/) seems to be free.
- [Coderberg.org](https://codeberg.org/) is a free, non-profit forge . It uses Forgejo, which "[includes all of Gitea](https://forgejo.org/faq/#are-migrations-from-gitea-to-forgejo-possible)". Gitea 1.20-dev has [DEB](https://docs.gitea.com/next/usage/packages/packages/debian) and [RPM](https://docs.gitea.com/next/usage/packages/packages/rpm) registries, but the current stable 1.19.3 doesn't.
- [Gemfury](https://fury.co/pricing) – not sure what's available for free but prices seem reasonable.

I've also come across [Packagecloud](https://packagecloud.io/pricing/), which has a free plan with 2GB storage and 10GB bandwidth.

I've not used any of these, so don't know enough to recommend any.

**Comment by variar** [comment]
Thank you! Gitea option is interesting. It should be easy to self-host.

**Comment by variar** [comment]
Turns out that github pages can be used to host rpm/deb repositories. Could someone try if that works?

For DEB (replace <ubuntu_release> with one of bionic, focal, jammy):
```
curl -sS https://klogg.filimonov.dev/klogg.gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/klogg.gpg
echo deb [signed-by=etc/apt/trusted.gpg.d/klogg.gpg] https://klogg.filimonov.dev/deb/<ubuntu_release> <ubuntu_release> utils | sudo tee -a /etc/apt/sources.list
```

For RPM (replace <oracle_release> with one of 7, 8):
```
/etc/yum.repos.d/klogg-rpm.repo
[Klogg]
name=Klogg
baseurl=https://klogg.filimonov.dev/rpm/oracle/<oracle_release>/amd64
gpgkey=https://klogg.filimonov.dev/klogg.gpg.key
enabled=1
```

**Comment by akwala** [comment]
> For DEB (replace <ubuntu_release> with one of bionic, focal, jammy):
> 
> ```
> curl -sS https://klogg.filimonov.dev/klogg.gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/klogg.gpg
> echo deb [signed-by=etc/apt/trusted.gpg.d/klogg.gpg] https://klogg.filimonov.dev/deb/<ubuntu_release> <ubuntu_release> utils | sudo tee -a /etc/apt/sources.list
> ```

There needs to be a leading slash in the `signed-by` value: `signed-by=/etc/apt/trusted.gpg.d/klogg.gpg`.

However, that location "[is completely and unconditionally trusted by apt](https://askubuntu.com/a/1307181/2673)." I put the key in `/usr/share/keyrings` which already had other keys – the post suggests  `/usr/local/share/keyrings`. And I replaced `/etc/apt/sources.list.d/klogg.list`, instead of appending to `/etc/apt/sources.list`. 
```
curl -sS https://klogg.filimonov.dev/klogg.gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/klogg.gpg
echo "deb [signed-by=/usr/share/keyrings/klogg.gpg] https://klogg.filimonov.dev/deb/jammy jammy utils" | sudo tee /etc/apt/sources.list.d/klogg.list
```

For other supported Ubuntu releases, substitute "jammy" with the appropriate release name.

**Comment by ofernandofilo** [comment]
using KDE neon... I did as recommended by akwala, then,

    sudo mousepad /etc/apt/sources.list

and removed this line:

    deb [trusted=yes] https://favpackage.jfrog.io/artifactory/klogg_deb/ jammy utils

it is working, thx _o/

**Comment by variar** [comment]
Thank you! I've updated installation guide in README.
