### ISSUE TITLE
'Search' brings up unmatched line

### ISSUE THREAD

**Issue by wiz0u** [variar/klogg#68]
When I search for example "ERROR" in my 8 MB log file, it also brings up some random lines that do not contains the text "ERROR".

Ignore case & Auto-refresh are unselected.
I tried with "Use parallel search" and "Enable search results cache" enabled and disabled, closing/reopening the file, always get the issue.

klogg build 19.3.0.369

**Comment by variar** [comment]
I'm sorry but from looking into the code I have no idea, how this can happen. Could you attach a sample log file that causes this behaviour?

There might be another issue with per-thread line endings cache, I'll make an option to disable it for testing (it really improves performance, so turning it off will hurt every day use cases)

**Comment by jeffjensen** [comment]
Not sure if this is the same issue scenario or not - I find search not working after multiple file replacements of the opened file.  For example, I opened a log file from test or app output and each test run overwrites the file (I have to re-click the Search button to have it update the contents, but that is a different issue!).  After many test runs, Klogg search output has mismatched and missing content so I restart Klogg and it is fine (I usually proactively restart Klogg after some test runs because I can't trust the search results).

**Comment by wiz0u** [comment]
It's been a while I did not observe the issue. I will try to reproduce it next week and take screenshot or give you more specifics

**Comment by variar** [comment]
Messed up results after several file updates might also be the same issue with broken line endings cache in ui thread. I'll try to reproduce this scenario.

**Comment by variar** [comment]
Added option to disable line ending cache. @jeffjensen please try to reproduce your issue in builds after 19.07.0.413

**Comment by variar** [comment]
The issue with unmatched lines can be reproduced on my work machine for non-portable version when loading file from network share and resizing matched results window during search.

**Comment by jeffjensen** [comment]
I'm glad you can repro.

I've been running the portable version (oh well! you repro with non-portable) to try the pre-release version and not seen the issue, even with the cache on.  Caveat is I have not been running klogg as much lately, but will again soon.

**Comment by wiz0u** [comment]
As for me, I haven't been able to reproduce recently
mostly using the portable version 19.6.0.401 with
perf.useParallelSearch=false perf.useSearchResultsCache=false perf.keepFileClosed=true
Now updating to latest non-portable release with default perf settings to see if there is any problem appearing.

**Comment by variar** [comment]
Issues on my work machine seem to be caused by perf.keepFileClosed=true. In this mode file is constantly reopened for reading lines and for some reason this is causing mismatches and even gabage output, especially when reading file from network share.

In build 19.07.0.422 I've changed keepFileClosed implementation so the file is not closed during whole search or index operations. Hope it helps and doesn't break file watching and updating. Don't have any windows box at home, will test this tommorow from the office.

**Comment by variar** [comment]
Can't reproduce anymore with latest build (>=422). Will close for now.

**Comment by jeffjensen** [comment]
I'm still seeing it with 19.7.0.432 (portable).

My use case is running a program that overwrites the log file opened in Klogg.  After multiple overwrites (5-10 or so?), the Search view results have lots of non-matching lines.

Restarting Klogg fixes it.

Settings:
![image](https://user-images.githubusercontent.com/63805/62469413-d7b02e80-b75d-11e9-8813-b0d0d8d9cafe.png)

**Comment by variar** [comment]
One possible cause for the issue could be logic of partial reindexing. If file is recreated with new data but the same or bigger size then partial index operation will be performed resulting in messed up index.  This can occur because file change notifications on network drives are done using polling. And even on local disk file change notifications can be delayed so klogg will miss original file truncation.

I've added check for that case (comparing md5 for index data and new file data in the same range) and from build 19.08.0.431 full index operation should be performed if file was changed in the range of already built index.

**Comment by variar** [comment]
On windows box hash check always leads to full reindex. Might be some issue with last line break.

**Comment by variar** [comment]
@jeffjensen could you check build 19.08.0.446 in your scenario?

**Comment by jeffjensen** [comment]
Thank you!  I used it all day today and have not noticed any Search result issues!  It is auto-refreshing correctly again.

**Comment by variar** [comment]
Thanks for testing
